### ISSUE TITLE
Live facial recognition

### ISSUE THREAD

**Issue by aysterberi** [aysterberi/ThesisProject#5]
Do live facial recognition.

- Don't take pictures every 33 milliseconds
- There is code that's commented, and ready to be used
- Threshold is an issue (maybe)
- TimerForRecognition, maybe put in already existing runnable instance (row 81 in Controller)

There is an example at: https://github.com/bytedeco

**Comment by Grusburk** [comment]
This has been done:

- Liverecognition now takes a testpicture (and puts it in the testfolder) then compare to that instead of a bufferdimage like we had before. As this seems to work alot better.

- Liverecognition now only happens when a face is found. (boolean made facefound instead of (roi !=null). So no more output spam. 

- Reworked method parameters (read refactor)  cause some werent needed anymore.

- Reworked takeTrainingpicture for liverecognition so it always saves the name as test.png and gets
overwritten  by next image taken. 

- Label created for latest person recognized. This with the help of Platform.runLater (we need this because label is on the uiThread and platform runLater sends the data to the uiThread.

**Comment by aysterberi** [comment]
Improvements could be made to this issue. More specifically it should be better at registering people that does not exist in the training sets as 'unknown'. It seems to lean towards being good at differentiating between different people, but not good at all at detecting people that are not a part of the training set.
